select * from PETSALE;

select SUM(SALEPRICE) from PETSALE;
select SUM(SALEPRICE) AS SUM_OF_SALEPRICE from PETSALE;
select MAX(QUANTITY) from PETSALE;
select AVG(SALEPRICE) from PETSALE;


select CAST(AVG( SALEPRICE / QUANTITY ) AS DECIMAL(6,2))  from PETSALE where ANIMAL = 'Dog';

select ANIMAL, CAST(AVG( SALEPRICE / QUANTITY ) AS DECIMAL(6,2)) as AVG_PRICE  from PETSALE
group by ANIMAL order by AVG_PRICE desc;


select ANIMAL, ROUND(SALEPRICE) as SALES_PRICE from PETSALE;
select LENGTH(ANIMAL) from PETSALE;

select MAX(LENGTH(ANIMAL)) from PETSALE;

select UCASE(ANIMAL) from PETSALE;



select DISTINCT(UCASE(ANIMAL)) from PETSALE;
select * from PETSALE where LCASE(ANIMAL) = 'cat';
select DAY(SALEDATE) from PETSALE where ANIMAL = 'Cat';

select COUNT(*) from PETSALE where MONTH(SALEDATE)='05';

select MONTH(SALEDATE) as 
MONTH, COUNT(MONTH(SALEDATE)) as COUNT
from PETSALE
group by MONTH(SALEDATE);


select *,  (SALEDATE + 2 DAYS) as TAKE_HOME_DATE from PETSALE;
select *, (CURRENT DATE - SALEDATE) as DATE_SINCE_PURCHASE, (SALEDATE + 2 DAYS) as TAKE_HOME_DATE  from PETSALE;